language: python
python:
  - 3.6
env:
  global:
    PATH:$PWD/bin:$PATH
  matrix:
    - TEST=traitlets-master-downstream-stable
    - TEST=jack-of-none
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade -r requirements.txt
  - bash install.sh
before_script:
  - bash show-installed.sh
script:
  - bash run_test.sh
