language: python
python:
  - 3.6
env:
  matrix:
    - TEST=traitlets-master-downstream-stable
    - TEST=jack-of-none
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade -r requirements.txt
  - |
    if [ -f $TEST/requirements.txt ]; then
      pip install --upgrade -r $TEST/requirements.txt
    fi
script: bash run_test.sh
