language: python
python:
  - 3.6
install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade -r requirements.txt
script: bash run_test.sh
matrix:
  env:
    - TEST=traitlets-master-downstream-stable
    # - TEST=jack-of-none